[project]
name = "phase0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tsadams1973", email = "tsa.adams@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.2",
]

[project.scripts]
phase0 = "phase0:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
